#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to
#your load-balancer IP (lb-01). Let’s also add other subdomains
#to make our life easier, and write a Bash script that will display
#information about subdomains

subdomain_info() {
	record_type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4}')
	dest=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $5}')
	echo "The subdomain $2 is a $record_type record and points to $dest"
	
}
if [ $# -eq 1 ]
then
	default_subdomains=("www" "lb-01" "web-01" "web-02")
	for sub_domain in "${default_subdomains[@]}"
	do
		subdomain_info "$1" "$sub_domain"
	done
elif [ $# -eq 2 ]
then
	subdomain_info "$1" "$2"
fi
