#!/usr/bin/env bash
# Install nginx on your web-01 server

sudo apt-get update

sudo apt-get -y install nginx

# to check if web dir exist and are writable
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx start
