#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu
#container’s Nginx installation from listening on port 80.
#Feel free to install whatever tool you need, start and destroy as
#many containers as you need to debug the issue.

config_file="/etc/nginx/sites-enabled/default"

# using sed and regex to find and change values
sed -i 's/[0-9]\+ default_server/80 default_server/' "$config_file"

sudo service nginx restart
