#!/usr/bin/env bash
#!/usr/bin/env bash
# Bash script that displays the content of the /etc/passwd file with specific information.

while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < /etc/passwd
