#!/usr/bin/env bash
# Bash script that displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

for file in *; do
  if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
    basename=$(basename "$file")
    filename=${basename#*-}
    echo "$filename"
  fi
done
