#!/usr/bin/env bash
#installing ufw and configuring to allow access to port 22, 80, 443
# By default allincoming are blocked and outgoing allowed

sudo apt update

sudo apt-get install ufw

sudo ufw default deny incoming

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw enable
