#!/usr/bin/env bash
# configuring new servers

sudo apt-get -y update

sudo apt-get -y install nginx

ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html

echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-enabled/default

sudo sed -i "/listen 80 default_server/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

sudo service nginx restart
