#!/usr/bin/env bash
# configuring new servers

app_name="nginx"

if command -v "$app_name" >/dev/null 2>&1; then
    :
else
    sudo apt-get update
    sudo apt-get install -y "$app_name"
fi

if [ ! -d "/etc/nginx/html" ]; then
    sudo mkdir -p /etc/nginx/html
fi

if [ ! -f "/etc/nginx/html/index.html" ]; then
    sudo touch /etc/nginx/html/index.html
fi

sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     add_header X-Served-By $HOSTNAME;

     location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
     }

     error_page 404 /404.html;
     location /404 {
        root /etc/nginx/html;
        internal;
     }
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
