#!/usr/bin/env bash
# Bash script that accepts one argument ,the script should run the whoami command under the user passed as an argument

if [ $# -gt 0 ]
then
	sudo -u "$1" whoami
	exit 1
else
	whoami
fi
