#!/usr/bin/env bash
# Running  nginx as nginx

#changing user to nginx
sed i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

#changing default port from 80 to 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

sudo -u nginx service nginx start
